<?php


define('CDT_SOCIAL_API_FACEBOOK_SDK_PATH', CDT_SOCIAL_API_PATH . 'facebook/sdk/');

define('CDT_SOCIAL_API_FACEBOOK_APP_ID', '239819902720786', true);
define('CDT_SOCIAL_API_FACEBOOK_APP_SECRET_ID', 'c2c49186be4e9a5ff0dc809d3f367158', true);

define('CDT_SOCIAL_API_FACEBOOK_API_USER_ID', '635427779');
define('CDT_SOCIAL_API_FACEBOOK_API_USER_TOKEN', '145634995501895|2.AQDzV_17XtPsljFL.3600.1314306000.1-635427779|QduOG-KSFNHaQ-2oJG5unlRyUWI');

define('CDT_SOCIAL_API_FACEBOOK_API_GRAPH_URL', 'https://graph.facebook.com/');
define('CDT_SOCIAL_API_FACEBOOK_API_URL', 'https://api.facebook.com/method/');


define('CDT_SOCIAL_API_FACEBOOK_API_FRIENDS', 'friends');
define('CDT_SOCIAL_API_FACEBOOK_API_POSTS', 'posts');
define('CDT_SOCIAL_API_FACEBOOK_API_STATUSES', 'statuses');
define('CDT_SOCIAL_API_FACEBOOK_API_PICTURE', 'picture');
define('CDT_SOCIAL_API_FACEBOOK_API_FEED', 'feed');
define('CDT_SOCIAL_API_FACEBOOK_API_HOME', 'home');
define('CDT_SOCIAL_API_FACEBOOK_API_INBOX', 'inbox');
define('CDT_SOCIAL_API_FACEBOOK_API_NOTIFICATIONS', 'notifications');
define('CDT_SOCIAL_API_FACEBOOK_API_FQL_QUERY', 'fql.query');
define('CDT_SOCIAL_API_FACEBOOK_API_COMMENTS', 'comments');
define('CDT_SOCIAL_API_FACEBOOK_API_LIKES', 'likes');

define('CDT_SOCIAL_API_FACEBOOK_POST_TYPE_STATUS', 'status');
define('CDT_SOCIAL_API_FACEBOOK_POST_TYPE_PHOTO', 'photo');
define('CDT_SOCIAL_API_FACEBOOK_POST_TYPE_LINK', 'link');
define('CDT_SOCIAL_API_FACEBOOK_POST_TYPE_VIDEO', 'video');

define('CDT_SOCIAL_API_SOCIAL_TYPE_NOTIFICATIONS', 1);


?>