<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 20-07-2011
 */ 
class EstadoPago { 
	
	//variables de instancia.
	
	private $cd_estadopago;
	
	private $ds_estadopago;
	

	//Constructor.
	public function EstadoPago() { 
				
		$this->cd_estadopago = '';
		
		$this->ds_estadopago = '';
		
		
	}

	//Getters	
		
	public function getCd_estadopago() { 
		return $this->cd_estadopago;
	}
		
	public function getDs_estadopago() { 
		return $this->ds_estadopago;
	}
	
	

	//Setters
	
	public function setCd_estadopago( $value ) { 
		$this->cd_estadopago = $value;
	}
	
	public function setDs_estadopago( $value ) { 
		$this->ds_estadopago = $value;
	}
	
	
} 
?>
