<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 15-08-2011
 */ 
class PaypalTx { 
	
	//variables de instancia.
	
	private $cd_paypal_tx;
	
	private $ds_txn_id;
	
	private $cd_pago;
	
	private $ds_paypal_tx;
	
	private $dt_fecha;
	
	private $ds_type;
	

	//Constructor.
	public function PaypalTx() { 
		
		
		$this->cd_paypal_tx = '';
		
		$this->ds_txn_id = '';
		
		$this->cd_pago = '';
		
		$this->ds_paypal_tx = '';
		
		$this->dt_fecha = '';
		
		$this->ds_type = '';
		
		
	}

	//Getters	
		
	public function getCd_paypal_tx() { 
		return $this->cd_paypal_tx;
	}
		
	public function getDs_txn_id() { 
		return $this->ds_txn_id;
	}
		
	public function getCd_pago() { 
		return $this->cd_pago;
	}
		
	public function getDs_paypal_tx() { 
		return $this->ds_paypal_tx;
	}
		
	public function getDt_fecha() { 
		return $this->dt_fecha;
	}
		
	public function getDs_type() { 
		return $this->ds_type;
	}
	
	

	//Setters
	
	public function setCd_paypal_tx( $value ) { 
		$this->cd_paypal_tx = $value;
	}
	
	public function setDs_txn_id( $value ) { 
		$this->ds_txn_id = $value;
	}
	
	public function setCd_pago( $value ) { 
		$this->cd_pago = $value;
	}
	
	public function setDs_paypal_tx( $value ) { 
		$this->ds_paypal_tx = $value;
	}
	
	public function setDt_fecha( $value ) { 
		$this->dt_fecha = $value;
	}
	
	public function setDs_type( $value ) { 
		$this->ds_type = $value;
	}
	
	
} 
?>
