<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 13-07-2011
 */ 
class Registracion { 
	
	//variables de instancia.
	
	private $cd_registracion;
	
	private $ds_codigoactivacion;
	
	private $dt_fecha;
	
	private $ds_nomusuario;
	
	private $ds_apynom;
	
	private $ds_mail;
	
	private $ds_password;
	
	private $oPais;
	
	private $ds_telefono;
	
	private $ds_domicilio;
	

	//Constructor.
	public function Registracion() { 
		
		$this->cd_registracion = '';
		
		$this->ds_codigoactivacion = '';
		
		$this->dt_fecha = '';
		
		$this->ds_nomusuario = '';
		
		$this->ds_apynom = '';
		
		$this->ds_mail = '';
		
		$this->ds_password = '';
		
		$this->ds_telefono = '';
		
		$this->ds_domicilio = '';
		
		
		$this->oPais = new Pais();
		
	}

	//Getters	
		
	public function getCd_registracion() { 
		return $this->cd_registracion;
	}
		
	public function getDs_codigoactivacion() { 
		return $this->ds_codigoactivacion;
	}
		
	public function getDt_fecha() { 
		return $this->dt_fecha;
	}
		
	public function getDs_nomusuario() { 
		return $this->ds_nomusuario;
	}
		
	public function getDs_apynom() { 
		return $this->ds_apynom;
	}
		
	public function getDs_mail() { 
		return $this->ds_mail;
	}
		
	public function getDs_password() { 
		return $this->ds_password;
	}
		
	public function getPais() { 
		return $this->oPais;
	}
		
	public function getDs_telefono() { 
		return $this->ds_telefono;
	}
		
	public function getDs_domicilio() { 
		return $this->ds_domicilio;
	}
	
		
	public function getCd_pais() { 
		return $this->oPais->getCd_pais();
	}
	

	//Setters
	
	public function setCd_registracion( $value ) { 
		$this->cd_registracion = $value;
	}
	
	public function setDs_codigoactivacion( $value ) { 
		$this->ds_codigoactivacion = $value;
	}
	
	public function setDt_fecha( $value ) { 
		$this->dt_fecha = $value;
	}
	
	public function setDs_nomusuario( $value ) { 
		$this->ds_nomusuario = $value;
	}
	
	public function setDs_apynom( $value ) { 
		$this->ds_apynom = $value;
	}
	
	public function setDs_mail( $value ) { 
		$this->ds_mail = $value;
	}
	
	public function setDs_password( $value ) { 
		$this->ds_password = $value;
	}
	
	public function setPais( $value ) { 
		$this->oPais = $value;
	}
	
	public function setDs_telefono( $value ) { 
		$this->ds_telefono = $value;
	}
	
	public function setDs_domicilio( $value ) { 
		$this->ds_domicilio = $value;
	}
	
	
	public function setCd_pais( $value ) { 
		$this->oPais->setCd_pais( $value );
	}

	public function createUsuario(){
		
		$oUsuario = new Usuario();
		$oUsuario->setCd_pais( $this->getCd_pais() );
		$oUsuario->setDs_apynom( $this->getDs_apynom() );
		$oUsuario->setDs_nomusuario( $this->getDs_nomusuario() );
		$oUsuario->setDs_password( $this->getDs_password() );
		$oUsuario->setDs_domicilio( $this->getDs_domicilio() );
		$oUsuario->setDs_mail( $this->getDs_mail() );
		$oUsuario->setDs_telefono( $this->getDs_telefono() );
		
		return $oUsuario;
	}
	
} 
?>
