<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011
 */ 
class AccionFuncion { 
	
	//variables de instancia.
	
	private $cd_accionfuncion;
	
	private $oFuncion;
	
	private $ds_accion;
	

	//Constructor.
	public function AccionFuncion() { 
		//TODO inicializar variables.
		
		
		$this->cd_accionfuncion = '';
		
		$this->ds_accion = '';
		
		
		$this->oFuncion = new Funcion();
		
	}

	//Getters	
		
	public function getCd_accionfuncion() { 
		return $this->cd_accionfuncion;
	}
		
	public function getFuncion() { 
		return $this->oFuncion;
	}
		
	public function getDs_accion() { 
		return $this->ds_accion;
	}
	
		
	public function getCd_funcion() { 
		return $this->oFuncion->getCd_funcion();
	}
	

	//Setters
	
	public function setCd_accionfuncion( $value ) { 
		$this->cd_accionfuncion = $value;
	}
	
	public function setFuncion( $value ) { 
		$this->oFuncion = $value;
	}
	
	public function setDs_accion( $value ) { 
		$this->ds_accion = $value;
	}
	
	
	public function setCd_funcion( $value ) { 
		$this->oFuncion->setCd_funcion( $value );
	}
	
} 
?>
