<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011
 */ 
class MenuGroup { 
	
	//variables de instancia.
	
	private $cd_menugroup;
	
	private $orden;
	
	private $width;
	
	private $nombre;
	
	private $action;
	
	private $cssclass;
	
	protected $oOpciones;
	
	//Constructor.
	
	
	function MenuGroup($nombre='',$w=0, $action='' ) {
		$this->ds_nombre = $nombre;
		$this->width=$w;
		$this->oOpciones = new ItemCollection();
		$this->ds_action = $action;
		$this->ds_cssclass='';
	}	

	//Getters	
		
	public function getCd_menugroup() { 
		return $this->cd_menugroup;
	}
		
	public function getOrden() { 
		return $this->orden;
	}
		
	public function getWidth() { 
		return $this->width;
	}
		
	public function getNombre() { 
		return $this->nombre;
	}
		
	public function getAction() { 
		return $this->action;
	}
		
	public function getCssclass() { 
		return $this->cssclass;
	}
	
	function getOpciones() {
		return $this->oOpciones;
	}	

	//Setters
	
	public function setCd_menugroup( $value ) { 
		$this->cd_menugroup = $value;
	}
	
	public function setOrden( $value ) { 
		$this->orden = $value;
	}
	
	public function setWidth( $value ) { 
		$this->width = $value;
	}
	
	public function setNombre( $value ) { 
		$this->nombre = $value;
	}
	
	public function setAction( $value ) { 
		$this->action = $value;
	}
	
	public function setCssclass( $value ) { 
		$this->cssclass = $value;
	}
	
	function setOpciones(ItemCollection $items){
		$this->oOpciones = $items;
	}
	
	function addMenuOption($nombre, $href, $active=false){
		$option  =  new MenuOption($nombre, $href, $active);
		$option->setMenuGroup( $this );
		$this->oOpciones->addItem( $option );
	}

	function addMenuSecureOption(Funcion $oFuncion, $nombre, $href, $active=false){
		$option  =  new MenuSecureOption( $oFuncion, $nombre, $href, $active );
		$option->setMenuGroup( $this );
		$this->oOpciones->addItem( $option );
	}
	

	
	function getMenuActivo(){
		$menuActivo = null;
		
		foreach($this->getOpciones() as $key => $opcion) {
			if ( $opcion->getBl_activo() ) {
				$menuActivo = $opcion;
				break;
			}				
		}
		
		return $menuActivo;
		
	}
	
	/**
	 * dada una lista de funciones, se determina si se tiene acceso o no
	 * al menuGroup.
	 * @param $funciones
	 */
	function tieneAcceso( ItemCollection $funciones = null ){
		$tiene = false;
		foreach($this->getOpciones() as $opcion) {
			$tiene = $opcion->tieneAcceso( $funciones );
			if ( $tiene ) 
				break;
		}				
		return $tiene;
	}	
} 
?>
