<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011
 */ 
class AccionFuncionFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('AccionFuncion');
		$oAccionFuncion = parent::build($next);
		
		 //TODO foreign keys
		 $funcionFactory = new FuncionFactory(); 
		 $oFuncion = $funcionFactory->build( $next );
		 
		 $oAccionFuncion->setFuncion( $oFuncion );
		 
		return $oAccionFuncion;
	}
} 
?>
