<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 29-06-2011
 */
class PagoFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Pago');
        $oPago = parent::build($next);

        if (array_key_exists('ds_estadopago', $next)) {
            $estadoFactory = new EstadoPagoFactory();
            $oPago->setEstadoPago($estadoFactory->build($next));
        }
     	if (array_key_exists('ds_nomusuario', $next)) {
            $oUsuarioFactory = new UsuarioFactory();
            $oPago->setUsuario($oUsuarioFactory->build($next));
        }
        return $oPago;
    }

}
?>
