<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 13-07-2011 
 */ 
class RegistracionTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function RegistracionTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = CDT_SEGURIDAD_REGISTRACION_CD_REGISTRACION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_REGISTRACION_DT_FECHA;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_REGISTRACION_DS_NOMUSUARIO;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_REGISTRACION_DS_APYNOM;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_REGISTRACION_DS_MAIL;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Registraciones";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oRegistracion = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oRegistracion->getCd_registracion(); break;
			
			case 1: $value= $oRegistracion->getDt_fecha(); break;
			
			case 2: $value= $oRegistracion->getDs_nomusuario(); break;
			
			case 3: $value= $oRegistracion->getDs_apynom(); break;
			
			case 4: $value= $oRegistracion->getDs_mail(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_registracion', 'cd_registracion');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'dt_fecha', 'dt_fecha');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'ds_nomusuario', 'ds_nomusuario');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(3), 'ds_apynom', 'ds_apynom');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(4), 'ds_mail', 'ds_mail');
	 	
	 	return $encabezados;	
	}
	
}
?>
