<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 20-07-2011
 */ 
class Pago { 
	
	//variables de instancia.
	
	private $cd_pago;
	
	private $ds_descripcion;
	
	private $dt_fecha;
	
	private $dt_fechacambioestado;
	
	private $oEstadoPago;
	
	private $oUsuario;
	

	//Constructor.
	public function Pago() { 
		
		
		$this->cd_pago = '';
		
		$this->ds_descripcion = '';
		
		$this->dt_fecha = '';
		
		$this->dt_fechacambioestado = '';
		
		$this->oEstadoPago = new EstadoPago();
		
		$this->oUsuario = new Usuario();
		
	}

	//Getters	
		
	public function getCd_pago() { 
		return $this->cd_pago;
	}
		
	public function getDs_descripcion() { 
		return $this->ds_descripcion;
	}
		
	public function getDt_fecha() { 
		return $this->dt_fecha;
	}
		
	public function getDt_fechacambioestado() { 
		return $this->dt_fechacambioestado;
	}
		
	public function getEstadoPago() { 
		return $this->oEstadoPago;
	}
	
		
	public function getUsuario() { 
		return $this->oUsuario;
	}
	
		
	public function getCd_estadopago() { 
		return $this->oEstadoPago->getCd_estadopago();
	}
		
	public function getCd_usuario() { 
		return $this->oUsuario->getCd_usuario();
	}
	

	//Setters
	
	public function setCd_pago( $value ) { 
		$this->cd_pago = $value;
	}
	
	public function setDs_descripcion( $value ) { 
		$this->ds_descripcion = $value;
	}
	public function setDt_fecha( $value ) { 
		$this->dt_fecha = $value;
	}
	
	public function setDt_fechacambioestado( $value ) { 
		$this->dt_fechacambioestado = $value;
	}
	
	public function setEstadoPago( $value ) { 
		$this->oEstadoPago = $value;
	}
	
	public function setUsuario( $value ) { 
		$this->oUsuario = $value;
	}
	
	public function setCd_estadopago( $value ) { 
		$this->oEstadoPago->setCd_estadopago( $value );
	}
	
	public function setCd_usuario( $value ) { 
		$this->oUsuario->setCd_usuario( $value );
	}
	
} 
?>
