<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011
 */ 
class MenuOptionDAO { 

	public static function insertarMenuOption(MenuOption $oMenuOption) { 
		$db = DbManager::getConnection(); 

		
		$cd_menuoption = $oMenuOption->getCd_menuoption();
		
		$nombre = $oMenuOption->getNombre();
		
		$href = $oMenuOption->getHref();
		
		$cd_funcion = $oMenuOption->getCd_funcion();
		
		$orden = $oMenuOption->getOrden();
		
		$cd_menugroup = $oMenuOption->getCd_menugroup();
		
		$cssclass = $oMenuOption->getCssclass();
		
		$descripcion_panel = $oMenuOption->getDescripcion_panel();
		

		$sql = "INSERT INTO menuoption (nombre, href, cd_funcion, orden, cd_menugroup, cssclass, descripcion_panel) VALUES('$nombre', '$href', $cd_funcion, '$orden', '$cd_menugroup', '$cssclass', '$descripcion_panel')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarMenuOption(MenuOption $oMenuOption) { 
		$db = DbManager::getConnection(); 

		
		$cd_menuoption = $oMenuOption->getCd_menuoption();
		
		$nombre = $oMenuOption->getNombre();
		
		$href = $oMenuOption->getHref();
		
		$cd_funcion = $oMenuOption->getCd_funcion();
		
		$orden = $oMenuOption->getOrden();
		
		$cd_menugroup = $oMenuOption->getCd_menugroup();
		
		$cssclass = $oMenuOption->getCssclass();
		
		$descripcion_panel = $oMenuOption->getDescripcion_panel();
		


		$sql = "UPDATE menuoption SET nombre = '$nombre', href = '$href', cd_funcion = $cd_funcion, orden = '$orden', cd_menugroup = '$cd_menugroup', cssclass = '$cssclass', descripcion_panel = '$descripcion_panel' WHERE cd_menuoption = $cd_menuoption "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarMenuOption(MenuOption $oMenuOption) { 
		$db = DbManager::getConnection(); 

		$cd_menuoption = $oMenuOption->getCd_menuoption();

		$sql = "DELETE FROM menuoption WHERE cd_menuoption = $cd_menuoption "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getMenuoptions(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM menuoption "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new MenuOptionFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantMenuoptions(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM menuoption "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getMenuOption(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM menuoption "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new MenuOptionFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
