<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011
 */ 
class MenuGroupDAO { 

	public static function insertarMenuGroup(MenuGroup $oMenuGroup) { 
		$db = DbManager::getConnection(); 

		
		$cd_menugroup = $oMenuGroup->getCd_menugroup();
		
		$orden = $oMenuGroup->getOrden();
		
		$width = $oMenuGroup->getWidth();
		
		$nombre = $oMenuGroup->getNombre();
		
		$action = $oMenuGroup->getAction();
		
		$cssclass = $oMenuGroup->getCssclass();
		

		$sql = "INSERT INTO menugroup (orden, width, nombre, action, cssclass) VALUES('$orden', '$width', '$nombre', '$action', '$cssclass')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarMenuGroup(MenuGroup $oMenuGroup) { 
		$db = DbManager::getConnection(); 

		
		$cd_menugroup = $oMenuGroup->getCd_menugroup();
		
		$orden = $oMenuGroup->getOrden();
		
		$width = $oMenuGroup->getWidth();
		
		$nombre = $oMenuGroup->getNombre();
		
		$action = $oMenuGroup->getAction();
		
		$cssclass = $oMenuGroup->getCssclass();
		


		$sql = "UPDATE menugroup SET orden = '$orden', width = '$width', nombre = '$nombre', action = '$action', cssclass = '$cssclass' WHERE cd_menugroup = $cd_menugroup "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarMenuGroup(MenuGroup $oMenuGroup) { 
		$db = DbManager::getConnection(); 

		$cd_menugroup = $oMenuGroup->getCd_menugroup();

		$sql = "DELETE FROM menugroup WHERE cd_menugroup = $cd_menugroup "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getMenugroups(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM menugroup "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new MenuGroupFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantMenugroups(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM menugroup "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getMenuGroup(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM menugroup "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new MenuGroupFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
