<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 29-06-2011
 */
class EstadoPagoFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('EstadoPago');
        return parent::build($next);
    }

}
?>
