<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 15-08-2011
 */ 
class PaypalTxFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('PaypalTx');
		$oPaypalTx = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oPaypalTx;
	}
} 
?>
