<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011 
 */ 
class MenuGroupManager implements IListar{ 

	public function agregarMenuGroup(MenuGroup $oMenuGroup) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		MenuGroupDAO::insertarMenuGroup($oMenuGroup);
	}


	public function modificarMenuGroup(MenuGroup $oMenuGroup) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		MenuGroupDAO::modificarMenuGroup($oMenuGroup);
	}


	public static function eliminarMenuGroup($id) { 
		//TODO validaciones; 

		$oMenuGroup = new MenuGroup();
		$oMenuGroup->setCd_menugroup($id);
		MenuGroupDAO::eliminarMenuGroup($oMenuGroup);
	}


	public function getMenugroups(CriterioBusqueda $criterio) { 
		return MenuGroupDAO::getMenugroups($criterio); 
	}


	public function getCantMenugroups(CriterioBusqueda $criterio) { 
		return MenuGroupDAO::getCantMenugroups($criterio); 
	}


	public function getMenuGroup(CriterioBusqueda $criterio) { 
		return MenuGroupDAO::getMenuGroup($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getMenugroups($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantMenugroups($criterio); 
	}


} 
?>
