<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011 
 */ 
class AccionFuncionTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function AccionFuncionTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = CDT_SEGURIDAD_ACCIONFUNCION_CD_ACCIONFUNCION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_ACCIONFUNCION_CD_FUNCION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_ACCIONFUNCION_DS_ACCION;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "AccionFunciones";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oAccionFuncion = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oAccionFuncion->getCd_accionfuncion(); break;
			
			case 1: $value= $oAccionFuncion->getFuncion()->getDs_funcion(); break;
			
			case 2: $value= $oAccionFuncion->getDs_accion(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_accionfuncion', 'cd_accionfuncion');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'cd_funcion', 'cd_funcion');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'cd_accion', 'cd_accion');
	 	
	 	return $encabezados;	
	}
	
}
?>
