<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011 
 */ 
class MenuOptionTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function MenuOptionTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_CD_MENUOPTION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_NOMBRE;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_HREF;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_CD_FUNCION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_ORDEN;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_CD_MENUGROUP;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_CSSCLASS;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_MENUOPTION_DESCRIPCION_PANEL;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Menuoptions";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oMenuOption = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oMenuOption->getCd_menuoption(); break;
			
			case 1: $value= $oMenuOption->getNombre(); break;
			
			case 2: $value= $oMenuOption->getHref(); break;
			
			case 3: $value= $oMenuOption->getCd_funcion(); break;
			
			case 4: $value= $oMenuOption->getOrden(); break;
			
			case 5: $value= $oMenuOption->getCd_menugroup(); break;
			
			case 6: $value= $oMenuOption->getCssclass(); break;
			
			case 7: $value= $oMenuOption->getDescripcion_panel(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_menuoption', 'cd_menuoption');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'nombre', 'nombre');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'href', 'href');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(3), 'cd_funcion', 'cd_funcion');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(4), 'orden', 'orden');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(5), 'cd_menugroup', 'cd_menugroup');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(6), 'cssclass', 'cssclass');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(7), 'descripcion_panel', 'descripcion_panel');
	 	
	 	return $encabezados;	
	}
	
}
?>
