<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 20-07-2011 
 */ 
class PagoManager implements IListar{ 

	public function agregarPago(Pago $oPago) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		PagoDAO::insertarPago($oPago);
	}


	public function modificarPago(Pago $oPago) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		PagoDAO::modificarPago($oPago);
	}


	public static function eliminarPago($id) { 
		//TODO validaciones; 

		$oPago = new Pago();
		$oPago->setCd_pago($id);
		PagoDAO::eliminarPago($oPago);
	}


	public function getPagos(CriterioBusqueda $criterio) { 
		return PagoDAO::getPagos($criterio); 
	}


	public function getCantPagos(CriterioBusqueda $criterio) { 
		return PagoDAO::getCantPagos($criterio); 
	}

	public function getPagoPorId($cd_pago) {
		$criterio = new CriterioBusqueda();
		$criterio->addFiltro('cd_pago', $cd_pago, "="); 
		return $this->getPago($criterio); 
	}
	
	public function getPago(CriterioBusqueda $criterio) { 
		return PagoDAO::getPago($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getPagos($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantPagos($criterio); 
	}


} 
?>
