<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 15-08-2011 
 */ 
class PaypalTxManager implements IListar{ 

	public function agregarPaypalTx(PaypalTx $oPaypalTx) { 
		//persistir en la bbdd.
		PaypalTxDAO::insertarPaypalTx($oPaypalTx);
	}

	public function getPaypalTxs(CriterioBusqueda $criterio) { 
		return PaypalTxDAO::getPaypalTxs($criterio); 
	}


	public function getCantPaypalTxs(CriterioBusqueda $criterio) { 
		return PaypalTxDAO::getCantPaypalTxs($criterio); 
	}


	public function getPaypalTx(CriterioBusqueda $criterio) { 
		return PaypalTxDAO::getPaypalTx($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getPaypalTxs($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantPaypalTxs($criterio); 
	}


} 
?>
