<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 20-07-2011 
 */ 
class PagoTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function PagoTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAGO_CD_PAGO;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAGO_DT_FECHA;
		$this->columnWidths[] = 30;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAGO_DT_FECHACAMBIOESTADO;
		$this->columnWidths[] = 30;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAGO_CD_ESTADOPAGO;
		$this->columnWidths[] = 60;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAGO_DS_DESCRIPCION;
		$this->columnWidths[] = 180;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAGO_CD_USUARIO;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Pagos";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oPago = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oPago->getCd_pago(); break;
			
			case 1: $value= FuncionesComunes::fechaHoraMysqlaPHP( $oPago->getDt_fecha() ); break;
			
			case 2: $value= FuncionesComunes::fechaHoraMysqlaPHP( $oPago->getDt_fechacambioestado() ); break;
			
			case 3: $value= $oPago->getEstadoPago()->getDs_estadopago(); break;
			
			case 4: $value= $oPago->getDs_descripcion(); break;
			
			case 5: $value= $oPago->getUsuario()->getDs_nomusuario(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_pago', CDT_PAGOS_GATEWAY_PAGO_CD_PAGO);
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'dt_fecha', CDT_PAGOS_GATEWAY_PAGO_DT_FECHA);
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'dt_fechacambioestado', CDT_PAGOS_GATEWAY_PAGO_DT_FECHACAMBIOESTADO);
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(3), 'ds_estadopago', CDT_PAGOS_GATEWAY_PAGO_CD_ESTADOPAGO);
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(4), 'ds_descripcion', CDT_PAGOS_GATEWAY_PAGO_DS_DESCRIPCION);
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(5), 'cd_usuario', CDT_PAGOS_GATEWAY_PAGO_CD_USUARIO);
	 	
	 	return $encabezados;	
	}
	
}
?>
