<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 15-08-2011 
 */ 
class PaypalTxTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function PaypalTxTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAYPAL_TX_CD_PAYPAL_TX;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAYPAL_TX_DS_TXN_ID;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAYPAL_TX_CD_PAGO;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAYPAL_TX_DS_PAYPAL_TX;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAYPAL_TX_DT_FECHA;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_PAGOS_GATEWAY_PAYPAL_TX_DS_TYPE;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "PaypalTxs";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oPaypalTx = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oPaypalTx->getCd_paypal_tx(); break;
			
			case 1: $value= $oPaypalTx->getDs_txn_id(); break;
			
			case 2: $value= $oPaypalTx->getCd_pago(); break;
			
			case 3:{ 
				$tx = str_replace("\n\r","<br />", $oPaypalTx->getDs_paypal_tx () ) ;
				$tx = str_replace("\n","<br />", $tx ) ;
				$tx = str_replace("\r","<br />", $tx ) ;
				$tx = substr( $tx, 0, 70) . " ... ";
				$value= $tx;
			
			} break;
			
			case 4: $value= $oPaypalTx->getDt_fecha(); break;
			
			case 5: $value= $oPaypalTx->getDs_type(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_paypal_tx', 'cd_paypal_tx');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'ds_txn_id', 'ds_txn_id');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'cd_pago', 'cd_pago');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(3), 'ds_paypal_tx', 'ds_paypal_tx');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(4), 'dt_fecha', 'dt_fecha');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(5), 'ds_type', 'ds_type');
	 	
	 	return $encabezados;	
	}
	
}
?>
