<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 20-07-2011 
 */ 
class EstadoPagoManager implements IListar{ 

	public function agregarEstadoPago(EstadoPago $oEstadoPago) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		EstadoPagoDAO::insertarEstadoPago($oEstadoPago);
	}


	public function modificarEstadoPago(EstadoPago $oEstadoPago) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		EstadoPagoDAO::modificarEstadoPago($oEstadoPago);
	}


	public static function eliminarEstadoPago($id) { 
		//TODO validaciones; 

		$oEstadoPago = new EstadoPago();
		$oEstadoPago->setCd_estadopago($id);
		EstadoPagoDAO::eliminarEstadoPago($oEstadoPago);
	}


	public function getEstadoPagos(CriterioBusqueda $criterio) { 
		return EstadoPagoDAO::getEstadoPagos($criterio); 
	}


	public function getCantEstadoPagos(CriterioBusqueda $criterio) { 
		return EstadoPagoDAO::getCantEstadoPagos($criterio); 
	}


	public function getEstadoPago(CriterioBusqueda $criterio) { 
		return EstadoPagoDAO::getEstadoPago($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getEstadoPagos($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantEstadoPagos($criterio); 
	}


} 
?>
