<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 15-08-2011
 */ 
class PaypalTxDAO { 

	public static function insertarPaypalTx(PaypalTx $oPaypalTx) { 
		$db = DbManager::getConnection(); 

		
		$cd_paypal_tx = $oPaypalTx->getCd_paypal_tx();
		
		$ds_txn_id = $oPaypalTx->getDs_txn_id();
		
		$cd_pago = $oPaypalTx->getCd_pago();
		
		$ds_paypal_tx = $oPaypalTx->getDs_paypal_tx();
		
		$dt_fecha = $oPaypalTx->getDt_fecha();
		
		$ds_type = $oPaypalTx->getDs_type();
		

		$sql = "INSERT INTO " . CDT_PAGOS_GATEWAY_TABLA_PAYPAL_TX   .  " (ds_txn_id, cd_pago, ds_paypal_tx, dt_fecha, ds_type) VALUES('$ds_txn_id', '$cd_pago', '$ds_paypal_tx', '$dt_fecha', '$ds_type')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getPaypalTxs(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM " . CDT_PAGOS_GATEWAY_TABLA_PAYPAL_TX   . " "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new PaypalTxFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantPaypalTxs(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM " . CDT_PAGOS_GATEWAY_TABLA_PAYPAL_TX   .  " "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getPaypalTx(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM " . CDT_PAGOS_GATEWAY_TABLA_PAYPAL_TX   .  " "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new PaypalTxFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
