<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011 
 */ 
class MenuOptionManager implements IListar{ 

	public function agregarMenuOption(MenuOption $oMenuOption) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		MenuOptionDAO::insertarMenuOption($oMenuOption);
	}


	public function modificarMenuOption(MenuOption $oMenuOption) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		MenuOptionDAO::modificarMenuOption($oMenuOption);
	}


	public static function eliminarMenuOption($id) { 
		//TODO validaciones; 

		$oMenuOption = new MenuOption();
		$oMenuOption->setCd_menuoption($id);
		MenuOptionDAO::eliminarMenuOption($oMenuOption);
	}


	public function getMenuoptions(CriterioBusqueda $criterio) { 
		return MenuOptionDAO::getMenuoptions($criterio); 
	}


	public function getCantMenuoptions(CriterioBusqueda $criterio) { 
		return MenuOptionDAO::getCantMenuoptions($criterio); 
	}


	public function getMenuOption(CriterioBusqueda $criterio) { 
		return MenuOptionDAO::getMenuOption($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getMenuoptions($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantMenuoptions($criterio); 
	}


} 
?>
