<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011
 */ 
class MenuOption { 
	
	//variables de instancia.
	
	private $cd_menuoption;
	
	private $nombre;
	
	private $href;
	
	private $cd_funcion;
	
	private $orden;
	
	private $oMenuGroup;
	
	private $cssclass;
	
	private $descripcion_panel;
	
	private $bl_activo;
	
	//Constructor.
	function MenuOption($nombre='', $href='#', $activo=false) {
		$this->ds_nombre =$nombre;
		$this->ds_href = $href;
		$this->bl_activo = $activo;
		$this->oMenuGroup = new MenuGroup();
	}	

	//Getters	
		
	function getBl_activo() {
		return $this->bl_activo;
	}
	
	public function getCd_menuoption() { 
		return $this->cd_menuoption;
	}
		
	public function getNombre() { 
		return $this->nombre;
	}
		
	public function getHref() { 
		return $this->href;
	}
		
	public function getCd_funcion() { 
		return $this->cd_funcion;
	}
		
	public function getOrden() { 
		return $this->orden;
	}
		
	public function getMenuGroup() { 
		return $this->oMenuGroup;
	}
		
	public function getCssclass() { 
		return $this->cssclass;
	}
		
	public function getDescripcion_panel() { 
		return $this->descripcion_panel;
	}
	
		
	public function getCd_menugroup() { 
		return $this->oMenuGroup->getCd_menugroup();
	}
	

	//Setters
	
	function setBl_activo($value) {
		$this->bl_activo = $value;
	}
	public function setCd_menuoption( $value ) { 
		$this->cd_menuoption = $value;
	}
	
	public function setNombre( $value ) { 
		$this->nombre = $value;
	}
	
	public function setHref( $value ) { 
		$this->href = $value;
	}
	
	public function setCd_funcion( $value ) { 
		$this->cd_funcion = $value;
	}
	
	public function setOrden( $value ) { 
		$this->orden = $value;
	}
	
	public function setMenuGroup( $value ) { 
		$this->oMenuGroup = $value;
	}
	
	public function setCssclass( $value ) { 
		$this->cssclass = $value;
	}
	
	public function setDescripcion_panel( $value ) { 
		$this->descripcion_panel = $value;
	}
	
	
	public function setCd_menugroup( $value ) { 
		$this->oMenuGroup->setCd_menugroup( $value );
	}

	/**
	 * dada una lista de funciones, se determina si se tiene acceso o no
	 * a la opción de menú.
	 * @param $funciones
	 */
	function tieneAcceso( ItemCollection $funciones = null ){
		return true;
	}	
} 
?>
