<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 04-07-2011 
 */ 
class FuncionTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function FuncionTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = CDT_SEGURIDAD_FUNCION_CD_FUNCION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = CDT_SEGURIDAD_FUNCION_DS_FUNCION;
		$this->columnWidths[] = 80;
		
	}

	public function getFiltros(){
		$filtro['orden']= 'ds_funcion';
		$filtro['descripcion']= CDT_SEGURIDAD_FUNCION_DS_FUNCION;
		$filtros[] = $filtro;
		
        return $filtros;
	}
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Funciones";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oFuncion = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oFuncion->getCd_funcion(); break;
			
			case 1: $value= $oFuncion->getDs_funcion(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_funcion', 'cd_funcion');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'ds_funcion', 'ds_funcion');
	 	
	 	return $encabezados;	
	}
	
}
?>
